PROG   <filename> [<start> [<end>]]  Program Orion EEPROM from file
prog: usage:  PROG <filename> [<start> [<end>]]
prog: can't open input file
prog: error evaluating <start> address parameter
prog: error evaluating <end> address parameter
prog: end of file reached before S7/S8/S9 record was read
prog: S9 record read - file closed normally
prog: checksum error in S-Record input file
prog: format error in S-Record input file; file is probably not S-Records
prog: error encountered programming data into EEPROM
