protoe -co -fbd32new.p BD32NEW.C
protoe -co -fdi_error.p DI_ERROR.C
protoe -co -fevs.p EVS.C
protoe -co -flpt.p LPT.C
protoe -co -fnewasm.p NEWASM.C
protoe -co -fnewdasm.p NEWDASM.C
protoe -co -fnewsym.p NEWSYM.C
protoe -co -fsio.p SIO.C
protoe -co -ftarget.p TARGET.C
